name: r26_frontend
description: R26 Research Frontend

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true