// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqtL6J5IJcihs78BkX3QG_7Fj4ilxAsbk',
    appId: '1:765224709282:web:829c943704eba02eca7bfb',
    messagingSenderId: '765224709282',
    projectId: 'intelligent-diary-r26-125',
    authDomain: 'intelligent-diary-r26-125.firebaseapp.com',
    storageBucket: 'intelligent-diary-r26-125.firebasestorage.app',
    measurementId: 'G-HHPP0CTN8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMborNrerB7OF_KsacweZ4YmjrxiQcsic',
    appId: '1:765224709282:android:1155fcc07c6983caca7bfb',
    messagingSenderId: '765224709282',
    projectId: 'intelligent-diary-r26-125',
    storageBucket: 'intelligent-diary-r26-125.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGHB7ZKNeZ904bDJk9oXUxr34tmDG4M0',
    appId: '1:765224709282:ios:f0bab519a888dc83ca7bfb',
    messagingSenderId: '765224709282',
    projectId: 'intelligent-diary-r26-125',
    storageBucket: 'intelligent-diary-r26-125.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGHB7ZKNeZ904bDJk9oXUxr34tmDG4M0',
    appId: '1:765224709282:ios:f0bab519a888dc83ca7bfb',
    messagingSenderId: '765224709282',
    projectId: 'intelligent-diary-r26-125',
    storageBucket: 'intelligent-diary-r26-125.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqtL6J5IJcihs78BkX3QG_7Fj4ilxAsbk',
    appId: '1:765224709282:web:3bda23c87adfc1a3ca7bfb',
    messagingSenderId: '765224709282',
    projectId: 'intelligent-diary-r26-125',
    authDomain: 'intelligent-diary-r26-125.firebaseapp.com',
    storageBucket: 'intelligent-diary-r26-125.firebasestorage.app',
    measurementId: 'G-WH9CZPHMHE',
  );
}
